### ISSUE TITLE
"Security option" in 4.2 Scripting API

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-architecture#11]
The document uses the term "security option" that is not aligned with the Scripting API.

My latest understanding was that scripts come along with "Security metadata" that define the execution environment, and thus access control for the Discovery/Client/Server APIs.

**Comment by mmccool** [comment]
I actually took out most mentions of security except for the two sections specifically about it in my revisions.     I just did a grep and in my last pull request "security option" no longer appears.

That said, I think this document needs a bit more detail on how security IS handled.   Since there is really no information whatsoever on certain aspects of the architecture (like the Discovery API) it's hard to criticize its security.

**Comment by mkovatsc** [comment]
It's in all the figures.

**Comment by mkovatsc** [comment]
Fixed in #23
