### ISSUE TITLE
6.5 Hypermedia Controls: Addtional examples of similar standards?

### ISSUE THREAD

**Issue by ashimura** [w3c/wot-architecture#246]
Currently the section "6.5 Hypermedia Controls" has IETF's CoRAL as only one example of similar standards but maybe it would be nicer to have some more related standards given we've been holding PlugFests including implementations of various standards.

**Comment by mkovatsc** [comment]
As I explained in the call, CoRAL and WoT are the first standards that define a machine-understandable concept of forms. This is new ground. Other standards lack this concept and thus struggle with the problem of describing requests. Since we two are the first there are no other examples, at least that I am aware of.

**Comment by mkovatsc** [comment]
Maybe mentioning CoRAL got me on the wrong track. For hypermedia controls in general, we can cite more work that is using links, e.g., CoRE Link Format, Resource Directory, Link Header (part of RFC 8288), OCF, and LWM2M.

**Comment by mkovatsc** [comment]
See #298
