### ISSUE TITLE
Markup all assertions 

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#249]
Introduce markups for RFC2119 assertions. 
Break up sentences that contain multiple assertions into individual sentences.

**Comment by mmccool** [comment]
This is essentially editorial and is actually invisible in the output, except for highlighting.   I think we need to merge the PRs currently in flight first...

**Comment by zolkis** [comment]
ReSpec does that for us. Explicit markups would make the raw text illegible.

**Comment by mlagally** [comment]
From the respec guide:

> RFC 2119
A very common construct in specifications is to use keywords defined in RFC 2119 which indicate precisely, using commonly agreed conventions, what requirements are placed on an implementation with what degree of strength (e.g., MUST, SHOULD NOT). All you need to do as an author is to include an all-caps MUST in your source and it will automatically get marked up as such (with the accompanying style applied to it afterwards).

@mmccool is that enough for your toolchain?

**Comment by k-toumura** [comment]
@zolkis ReSpec only markup a word that matches RFC2119 keywords.
It can't markup a sentence which contains RFC2119 keywords.

**Comment by zolkis** [comment]
>  It can't markup a sentence which contains RFC2119 keywords.

In W3C specs we don't need to markup _sentences_ with RFC2119 keywords. It is sections that can be normative or informative. By default, a sentence that is in a normative section is normative. There could be multiple RFC2119 keywords in a single sentence, so marking up a sentence doesn't seem to help much.

**Comment by k-toumura** [comment]
I think this markup is to create an implementation report, like Thing Description document (see https://github.com/w3c/wot-thing-description#implementation-report ).

**Comment by zolkis** [comment]
It should be the other way around: please fix the assertions script, rather than messing up the spec.

**Comment by takuki** [comment]
My understanding is @mmccool 's toolings support a kind of [extreme programming](https://en.wikipedia.org/wiki/Extreme_programming) for writing and testing the specs. Personally in practice, I feel it is very useful.

**Comment by zolkis** [comment]
It's a helper, and by picking sentences out of the spec doesn't guarantee correct implementation, nor test coverage. Implementors should still read the spec manually and validate implementations with tests. 

The tool currently makes unreasonable secondary markup requirements to the spec prose, including generating unique id's for each span and having each RFC2119 in a separate span. It makes editing hard and clutters the raw text. I wonder why it's not done by sweeping the text for RFC2119 words (they all in block capital to discern from informative variants) and take the surrounding sentences if that is needed. 

It's a secondary issue that IMHO the table in the implementation report creates a false illusion of capturing all normative requirements, since it only works at syntactic level. One should always check implementations against the spec itself, and not against a digest that is syntactically generated from the spec. But if that's what is wanted, fine, but making that digest shouldn't require messing up spec prose.

**Comment by mmccool** [comment]
See https://github.com/w3c/wot-architecture/pull/285.   Zoltan, I understand your concerns but we do need to generate an implementation report and this is the easiest way.
