### ISSUE TITLE
Remove "Scripting Runtime" as a term, use execution environment

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#278]
Delete it from terminology section.
Remove section 8.3
Call out the sandboxing aspect of the application execution environment in section 8.2
update intro text in section 8

**Comment by zolkis** [comment]
There is a distinction between WoT Runtime (that implements the WoT network interface) and a Scripting Runtime (which is an optional part of the WoT Runtime and provides runtime functionality to run scripts).
Sandboxing can be part of Scripting Runtime, but usually one Scripting Runtime is one sandbox.
Removing the term Scripting Runtime will result in the earlier situation of confusing the two.

**Comment by mkovatsc** [comment]
The main point of the discussion was that, even when no scripting is used and there is no scripting runtime, the WoT Runtime must still be able to instantiate the ExposedThing and ConsumedThing software instances and provide an API toward the application code. In this sense, there is no point to emphasize a scripting runtime system that may or may not be used as part of the WoT Runtime.

**Comment by zolkis** [comment]
> and provide an API toward the application code

No, this was not part of the discussions in the WG. Is that now suddenly a mandatory requirement (you used "must")? If yes, what API must that be?

I don't think there is any mandatory requirement that a WoT Runtime MUST expose any kind of API towards applications. Would you give a source to where was this even discussed as a requirement?
Even the standardized Scripting API is optional, now you suddenly want to make exposing a non-standard application interface a mandatory part of implementations???

What the discussions have been about in my interpretation: 
- a WoT Runtime is the software stack needed to instantiate Things that can communicate via the WoT network interface using WoT interactions. That SW stack can be an OS + libraries + applications flashed to the HW or otherwise provisioned: but we never specified how should that happen except that the Scripting API is one way to implement applications (that is standardized in the WG, according to the charter).
- the WoT Runtime includes handling security metadata (in scope for the WG work) and provisioning mechanism (out of scope for the WG work).

Since there was a confusion during the discussions between WoT Runtime and scripting runtimes (such as an ECMAScript runtime, or Lua runtime or Python runtime), it is even more likely that outsider readers might get confused, too, so we felt the need to give definitions for both in the Architecture document. 

>  there is no point to emphasize a scripting runtime system that may or may not be used as part of the WoT Runtime

That I agree with: this relationship can be indeed omitted, but the roles should be defined clearly and separately.
In reality it can get even more complex, for instance in the Zephyr OS, JerryScript is used as a scripting runtime, but there is no WoT Runtime: that can be implemented either natively in C, providing a way to run WoT scripts in JerryScript, or the WoT Runtime can be implemented inside the Zephyr scripting runtime (JerryScript), and the WoT Scripting Runtime inside the WoT Runtime in this case.
So it doesn't really matter which is part of which, but it matters to clarify the roles of the WoT Runtime and the WoT Scripting Runtime.

If you want to delete that from the Architecture document, we should add it and its explanation to the Scripting spec.

**Comment by mkovatsc** [comment]
> No, this was not part of the discussions in the WG. Is that now suddenly a mandatory requirement (you used "must")? If yes, what API must that be?

Any kind of API because a WoT Runtime for which nobody can define any behavior or application logic is useless.

How do you "instantiate Things" or write applications without any kind of API?

**Comment by mkovatsc** [comment]
See PR #291

**Comment by zolkis** [comment]
See the [comment](https://github.com/w3c/wot-architecture/pull/291#discussion_r281034656).

**Comment by zolkis** [comment]
> Any kind of API because a WoT Runtime for which nobody can define any behavior or application logic is useless.

It's not useless, as in the case of a WoT Runtime without Scripting support, the applications are very likely part of the image. Of course every implementation is free to offer a proprietary API to applications, but this is not mandatory, whereas you suggested it was.

**Comment by zolkis** [comment]
Actually I see there is a new kind of confusion: the untold assumption on how applications would be deployed. This reinforces my opinion that provisioning and deployment scenarios should not be out of scope in WoT, because this leads to various confusions and assumptions.

**Comment by mkovatsc** [comment]
Considering the discussions among the participats in the call, it seems to be only your assumption that this has something to do with application deployment and that applications are assumed to be deployed independent from Servients. This might be due to a very script-centric view.

Also for creating images that include WoT Runtime code and application code, there must have been a way to combine WoT Runtime functionality with application functionality: an API.

**Comment by zolkis** [comment]
No, there is a possibility that I write both the WoT Runtime AND the applications in JavaScript and deploy them BOTH either as a single platform application, or just flash them to the device in a single image.

**Comment by zolkis** [comment]
You cannot talk about an "API" without specifying what API do you mean. 
Also, you cannot make an API normative that is not defined.

**Comment by mlagally** [comment]
@mkovatsc @zolkis Please participate in tomorrow's architecture call (8am-10amCEST) to resolve the discussion.

**Comment by mkovatsc** [comment]
@zolkis please prepare by reading:
* Section 8 has longly been clearly marked as non-normative and there is no RFC 2119 language
* Sources for the term "execution context"; on Google you will see that all relevant hits are for JavaScript/ECMAScript; furthermore, the "execution context" is at a function execution level comparable to a stack frame -- not what we need for isolation

**Comment by zolkis** [comment]
> the "execution context" is at a function execution level comparable to a stack frame  

@mkovatsc please prepare by reading about ECMAScript execution contexts which are not what you described.
http://www.ecma-international.org/ecma-262/9.0/index.html#sec-execution-contexts 

I made this point several times: since there is no universal terminology for scripting runtime concepts, and since the current Scripting API is ECMAScript, which already has standardized terms that prospective implementers are already familiar with, we should borrow from there the scripting runtime related terms that we use in the Architecture document, instead of inventing own terminology based on non-standard terms collected from various non-specified sources.

**Comment by mkovatsc** [comment]
> The execution context stack is used to track execution contexts. The running execution context is always the top element of this stack. A new execution context is created whenever control is transferred from the executable code associated with the currently running execution context to executable code that is not associated with that execution context. The newly created execution context is pushed onto the stack and becomes the running execution context.

**Comment by zolkis** [comment]
Read on: an execution context contains all implementation specific state necessary to track code execution, including environment (local and/or global), global objects, intrinsic objects, templates, originating script etc. So it's a bigger concept than just the [execution environment](http://www.ecma-international.org/ecma-262/9.0/index.html#sec-lexical-environments).

That is why I thought that using "execution context" would make more sense than using "execution environment" (while I understand that you meant "environment" in a broader sense than it is used in ECMAScript - it's anyway an overloaded term).

You can use whichever term in Architecture doc, but there will be confusion if the terms used in Scripting (which uses ECMAScript terms) will be different from the terms defined in Architecture.
