### ISSUE TITLE
Security Considerations

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-architecture#32]
@mmccool : We still need content for the section "Security Considerations".

That section should clarify that we are primarily describing exsiting IoT platforms and their existing security mechanisms. Thus, in general the security considerations for each IoT platform used apply. Furthermore, we need to summarize what users of WoT building blocks need to consider (e.g., more accessible information might attract more attackers, TDs might leak information, TDs need to checked like any other information consumed on the Web, etc.

Can the security Task Force provide such a text?

**Comment by mmccool** [comment]
Yes, there is some material that ended up in the TD document that should be moved to this document instead as it is of a more general nature.   I plan to create a pull request relative to your restructured version...

**Comment by mmccool** [comment]
Given the timing though we might have to leave those sections empty for now (for the FPWD) but can create PRs to update them ASAP.

**Comment by mkovatsc** [comment]
We need at least an Editor's Note to explain the roadmap.

**Comment by mkovatsc** [comment]
Added Editor's Note.
Up to Security Task Force now...

**Comment by mmccool** [comment]
Thank you.   In a separate issue (#30 Consistency) I responded to an issue that the security section can get very long.  Even to *mention* all the considerations, let alone the threat model, etc. or even to list the *references* will take a lot of space, and will distract people from the meat of the proposal.  There is also an issue that some "cross-cutting" concerns impact more than one architectural component (for instance, TD and Scripting) and we will end up repeating ourselves.

Therefore, I strongly suggest we create a separate deliverable, call it "Web of Things Security Considerations".   We can then (a) summarize the main points in each other deliverable, focusing on issues especially relevant to that deliverable (b) still publish all the details where people can find them, but without distracting people from the main deliverables.

We already arranged for a separate repo, so this will not be difficult to proceed with.

**Comment by mmccool** [comment]
During the Security TF meeting yesterday we discussed the idea of having a separate security deliverable and then just summaries in each of the other documents to both cover all the bases that need to be covered AND keep the complexity of the security sections other deliverables under control.   It was agreed that this was reasonable, with the proviso that any normative points (for example, specific fields in the TD or API calls) should go in the other deliverables and the security document would just be informative (although we do need to publish it in a way we can refer to from the other documents, eg as a W3C note etc).

So that's what we'd like to do.  As discussed before, I think we should create a separate w3c/wot-security repo for this but will use the w3c/wot/security-privacy directory for now.

I'm going to shortly file pull requests to explain this in the Editor's notes in each deliverable and link to w3c/wot/security-privacy and we will start consolidating our work there.   I think the summaries to go into each of the other deliverables should happen last.

**Comment by mkovatsc** [comment]
We now have the https://github.com/w3c/wot-security/ repository and Editor's Notes and links from the Architecture draft. I consider this closed.
