### ISSUE TITLE
Editorial Cleanup - search and replace

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#322]
This issue is a bucket for all editorial tasks, that can be performed by a simple query replace etc.
Please add items to the list below:

- decapitalize Building Blocks

**Comment by k-toumura** [comment]
minor editorial cleanups:
- Abstract: "intial" -> ?
- Section 3:
  -  "dimm" -> "dim"
  - "completeted" -> "completed"
  - "in order to to ease" -> "in order to ease"
- Section 4.1.2.1: "Profinet" -> "PROFINET" ?
- Section 4.1.11: "... weather predictions, etc reduced cost." -> "... weather predictions, etc. reduces cost."?
- Section 6.3: "concete" -> "concrete"
- Section 6.5.1: "serialised" -> "serialized"
- Section 6.5.2: "compared compared" -> "compared"
- Section 7.2: "WebSockets" -> "WebSocket"
- Section 8: `As defined in <a href="sec-wot-servient-architecture-high-level"></a>` -> `As defined in <a href="#sec-wot-servient-architecture-high-level"></a>`
- Section 8: "scripting languague" -> "scripting language"
- Section 8.2: "precicely" -> "precisely"
- Section 8.3: "specificiation" -> "specification"
- Section 8.4: "access my be" -> "access may be"?
- Section 8.7: "Echonet Lite" -> "ECHONET Lite", "BACNET" -> "BACnet"
- Section 9.2.3: "Web Socket" -> "WebSocket"

- References:
  - CoRE-RD: draft-11 is expired.  Should we use -20? (expires in 2019-9-12)
  - Y.2070: Should we use Y.4409 or Y.4409/Y.2070? (in [ITU-T Y.2070 page](https://www.itu.int/rec/T-REC-Y.2070-201501-I/en):  _Former ITU-T Y.2070 renumbered as ITU-T Y.4409 on 2016-02-05 without further modification and without being republished._)

**Comment by mkovatsc** [comment]
* check for "interaction(s)" that mean "Interaction Affordance(s)" and fix

**Comment by mkovatsc** [comment]
* "e.g. " --> "e.g., "
* "i.e. " --> "i.e., "
* "c.f., " --> "c.f. " (yes, no comma here)
* "..isation" --> "...ization" (also "..ize" for corresponing verbs)

**Comment by mlagally** [comment]
there's no occurrence of c.f.

**Comment by mkovatsc** [comment]
I thought this is a collected for common search and replace actions?

**Comment by mlagally** [comment]
yes. I'm addressing them at this moment, see my latest PR.

**Comment by k-toumura** [comment]
>   * Y.2070: Should we use Y.4409 or Y.4409/Y.2070? (in [ITU-T Y.2070 page](https://www.itu.int/rec/T-REC-Y.2070-201501-I/en):  _Former ITU-T Y.2070 renumbered as ITU-T Y.4409 on 2016-02-05 without further modification and without being republished._)

Current CR-candidate-4 uses `Y.4409/Y.2070` for reference ID, but `/`(slash) can not be used as reference ID (see [SpecRef's JSON schema](https://github.com/tobie/specref/blob/master/schemas/raw-reference.json#L7) ).

How about using `Y.4409-Y.2070`?

**Comment by k-toumura** [comment]
- [ ]  Section 7.3, third paragraph: `[[?wot-scripting-api]` -> `[[?wot-scripting-api]]` (one more closing bracket)

**Comment by mkovatsc** [comment]
`[[?wot-scripting-api]` was not fixed, I will commit this fix directly to the master.

**Comment by mkovatsc** [comment]
Fixed.
