### ISSUE TITLE
define "Private security (meta)data"

### ISSUE THREAD

**Issue by samuelweiler** [w3c/wot-architecture#380]
The meaning of this term in section 8.5 and 10 is not clear.  I suspect mitigation of this confusion require more than merely adding a definition - there may be some deeper issue here.

**Comment by mlagally** [comment]
The term "private security data" is used to describe information, that can be used to protect communication channels, perform authorization and authentication to restrict access to the thing, such as private keys for assymetric encryption, credentials, password files etc.

Management of this data is out of scope of the WoT architecture and Thing Description.
It is strongly recommended in the chapter "10.1.1 Thing Description Private Security Data Risk" to not use
private security data in a TD. 

Quote from chapter 10.1: 
> TDs are designed to carry only public security data. Producers of TDs must ensure that no private security information is included in TDs. There should be a strict separation of public and private security data. A TD should contain only public security information, letting Consumers know what they need to do to access as system if and only if they have authorization. Authorization in turn should be based on separately managed private information.

Proposed resolution:
- Add adefinition of "Private Security Data" to the spec.
- Rename "Private security metadata" in chapter 8.5 to "Private security data"
- Add a sentence to chapter 8.5 to explain that private security configuration contains private security metadata

**Comment by mlagally** [comment]
we reviewed the PR in call on 22.8. and closed the issue.

**Comment by mlagally** [comment]
Hi @samuelweiler,
many thanks for flagging a potential problem of the definition of private security data.

Unfortunately it is difficult for me understand your exact concerns, which part of the text causes confusion?

The intention of the text is to state:

- private security data (such as trust chains, private keys, ...) may be managed by the WoT runtime
- private security data is not accessible to applications and handled transparently by protocol bindings
- don't ever put private security data into a TD

Do these points address your concerns?
If you see a deeper issue, please call it out, so we can address it quickly.

**Comment by mlagally** [comment]
Aligning terminology in:
https://github.com/w3c/wot-architecture/pull/385

**Comment by mmccool** [comment]
Notes:
1. We decided to use "metadata" when we are describing something and "data" for actual content.   So, for example, there is "communications metadata" for descriptions of the protocol used to avoid confusion with "communications data" which is the actual data on the wire (a sensor measurement, for example).   The term "public security metadata" is metadata in this sense since it describes the security mechanism(s) used (OAuth2, Basic auth, JWT, etc), but not the concrete data (such as keys, including public keys).  
2. Technically, the "private security data" is in fact concrete data (eg concrete private keys), so this PR updates the spec to use that term consistently (rather than "private security configuration" or "private security metadata").
3. The term "private" here is used in the sense of "secret" as opposed to "associated with an individual".   This follows usage in security contexts, for example "public and private keys".   We could use "secret" here but that would be inconsistent with accepted usage.

**Comment by mlagally** [comment]
PR: https://github.com/w3c/wot-architecture/pull/396
