### ISSUE TITLE
Document lacks sufficient detail to understand how privacy-sensitive information flows through the system

### ISSUE THREAD

**Issue by snyderp** [w3c/wot-architecture#390]
The standard deals with a great deal of privacy sensitive information (identifiers are just one of them).  The document lacks sufficient detail to evaluate the privacy details / aspects of the described system.

Examples (non-exhaustive) of such un-addressed details include:
* how are identifiers generated
* who are they shared with
* how can they be revoked
* what is their lifetime
* how is permission given to generate these identifiers

**Comment by mlagally** [comment]
Architecture call on Oct 10th:

Thanks very much to the PING group for their review and the useful comments.

We discussed that we need to better explain our goal is to define an **Abstract Architecture** that does not prescribe all aspects of a concrete system.
The architecture document explains the basic concepts and defines a conceptual framework such as the Interaction affordances and interaction patterns and gives definitions for the architectural components. 
This is similar to the definition of SOA or of RESTful architectures.

We are adressing a new area of systems that go beyond traditional Web architectures, so we need to lay the groundwork wrt. requirements, concepts and terminology framework.
Because this is an **Abstract Architecture** definitions of concrete mechanisms (for example to handle identifiers and other privacy aspects) are out of scope.

This is not because privacy is not important, but because all concrete mechanisms are out of scope of an abstract architecture.

However in the next charter period we will consider extending the architecture framework with definitions to address device and information lifecycle.

We agreed to clarify the current architecture document by adding a section to the introduction stating:
- Since we are addressing a new area, we need to have an abstract architecture document to define a basic conceptual framework.
- The scope of the current abstract architecture does not define concrete mechanisms.
- However additional conceptual features will be addressed in a future revision of the document, such as an abstract device and information lifecycle.
- We don't prescribe any implementation.
- Privacy is important, and we discuss mitigation of privacy issues in section 10.
https://www.w3.org/TR/2019/CR-wot-architecture-20190516/#sec-security-considerations

To clarify that this is not a concrete implementation specification: 
- We will rename Section 8 to "Abstract servient architecture"
- We will rename Section 9 to "Example WoT Deployments"

**Comment by mlagally** [comment]
We will address these points in:
https://github.com/w3c/wot-architecture/issues/392
https://github.com/w3c/wot-architecture/issues/391
