### ISSUE TITLE
Property affordances claimed to always readable

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-architecture#412]
In the [Property Affordance](https://w3c.github.io/wot-architecture/#properties) of the document, it is mentioned that ` The state exposed by a Property MUST be retrievable (readable)`. Whereas the TD spec says ([here](https://w3c.github.io/wot-thing-description/#propertyaffordance)) that they can read, not MUST be read. Also, the vocabulary of the TD spec would need quite a substantial change to allow such a mandatory value.

I am not sure if this belongs to the TD spec or here, but logically there could be writeOnly properties in a Thing, thus requiring a change in the architecture document.

**Comment by mlagally** [comment]
Here's the full text of the paragraph, to allow discussion of the issue in context:

`A Property is an Interaction Affordance that exposes the state of the Thing. The state exposed by a Property MUST be retrievable (readable). Optionally, the state exposed by a Property MAY be updated (writeable). Things MAY choose to make Properties observable by pushing the new state after a change (cf. Observing Resources [RFC7641]). Write-only state should be updated through an Action.`

The intention of the text (which was contributed by Matthias) is to define a contract for properties that always permits read access to a property. "writeOnly" state updates should be done via actions.

Before we determine the required changes of a spec, and which spec to change (TD or architecture), we should agree on the desired behavior.
AFAIK the TD spec remains silent about the result of reading a "writeOnly" property, i.e. there could be variations in the behavior that range between returning different values, e.g. "undefined", "0", "1", "error" or indicating errors at protocol level.
This is pretty ambiguous and will cause potential interop issues.

It is questionable that the write-only case occurs frequently, and the design principle implied by the current text in the architecture spec is quite natural, i.e. to handle write-only properties via actions, which completely eliminates any ambiguities/interop problems.

**Comment by egekorkan** [comment]
> It is questionable that the write-only case occurs frequently, 

I totally agree with this.

> AFAIK the TD spec remains silent about the result of reading a "writeOnly" property

This is also valid for writing to a `readOnly` property.

I think the main reason for readOnly and writeOnly was to be able to model the data of property if it is an object (see [here](https://w3c.github.io/wot-thing-description/#example-26)). This also aligns with JSON Schema since it also aims to define data being sent or received. 
However, this way of thinking causes a problem when we talk on the interaction level.
Another reason to use these two words was that the word writeable was causing issues since people were writing `writeable` and `writable`. See issue in TD [here](https://github.com/w3c/wot-thing-description/issues/209)

**Comment by mlagally** [comment]
arch call on 5.12.:
- architecture and TD spec are consistent, there's no conflicting language.
- TD spec may require a clarification for 1.1 release.
- Filed #854

**Comment by hspaay** [comment]
Sorry for the [cross post](https://github.com/w3c/wot-binding-templates/issues/107) but since this issue is still open it seems like a good place to add a perspective.

> The 'readOnly' property name is chosen because of the ownership (or document producer) perspective, not the consumer perspective. Eg "don't touch my stuff" instead of 'here is what you can do'. Looks like an unfortunate mixup in perspective that will live likely live long ever after.

Also consider that in order to explain the use of readOnly and writeOnly the terms readable and writable are used, which indicates that they are better terms to begin with. Would you rather stick to a spec that is non-intuitive because its a spec or do you prefer ease of use and intuitive terminology? Also consider the time, effort that goes into explaining things and fixing bugs because it was confusing. Now is a better time to fix a problem than tomorrow :)

**Comment by mlagally** [comment]
Arch call on 17.12.:
to be revisited in next call.

**Comment by mlagally** [comment]
I recall conversations about this from >1 year ago, and it keeps coming back. I suggest to not have any requirements on readOnly writeOnly in the architecture and TD but just permit both.

The profile spec however should introduce this practical constraint that all properties can be read. Otherwise the semantics of readallproperties becomes messy.

**Comment by egekorkan** [comment]
> Otherwise the semantics of readallproperties becomes messy.

I think that this is fine, writeallproperties has the same problem that not every property is writeable.
