### ISSUE TITLE
Editorial issues on PR

### ISSUE THREAD

**Issue by mryuichi** [w3c/wot-architecture#437]
I found some editorial issues in section 4.

(1) In 4.1.13 Connected Car, the same paragraphs appear twice in the beginning and the end of this section.
"Monitoring of operation status ..." are duplicated.

(2) In 4.2.4 Smart Home Gateways, case notations for "Smart Home Gateway" are different. We can see "Smart Home Gateway", "Smart Home gateway", and "smart home gateway".
Should be unified to "Smart Home Gateway”?

(3) In the following section, since there is only one subsection, it may be omitted.
The title of "Section 4.1.13.1 Connected Car Example" may be omitted.
The title of "Section 4.1.2.1 Example: Smart Factory" may be omitted. Instead how about change the title of 4.1.2 "Industrial" to "Smart Factory"?

**Comment by mlagally** [comment]
Thanks @mryuichi for these useful comments.

I have created a PR for 1 and 2: https://github.com/w3c/wot-architecture/pull/439
On #3 I prefer to keep the examples in a separate subsection, since I think we will incorporate additional industrial use cases.
I hoe we will also extend the connected car section.

**Comment by mlagally** [comment]
Arch call on Dec 17th:
Issues were discussed, addressed, closing the issue.
