### ISSUE TITLE
Define terminology Thing Template

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#454]

**Comment by sebastiankb** [comment]
For me, the TDT is derived from the TD model. In addition there are no restrictions such as monitory terms as we know from the TD model (e.g., title, security). We have to define what is the minimum expectations of a TDT and how to identify a TDT when it is exchanged.

**Comment by zolkis** [comment]
Right, the minimum content is important.
Also, completeness would be important, e.g. should they contain all interaction definitions etc, as opposed to a "partial TD" (that can be either a formal term or common term that refers to a subset of the TD, e.g. the - complete or incomplete - definition of a single or multiple interactions).

**Comment by egekorkan** [comment]
I also agree that defining the minimum and in a way some sort of a maximum should be also discussed. 
- Maximum: What terms would make a TDT a "complete" TD? From my point of view, a TDT cannot contain an `id` field or `href`s that resolve to a specific device, i.e. if there is domain name or IP address. There we can say that `href` of a form MUST contain a URI variable if an `href` exists at all.
- Minimum: I think the minimum will be constrained on how one can identify a TDT. Also we should definitely talk about what happens to the `@context` value. Should a TD and TDT have the same context, should TDT have a different context or should it extend the TD context with another one?

**Comment by mlagally** [comment]
We should have a discussion based on requirements in next week's arch call.
Please review https://github.com/w3c/wot-architecture/blob/master/REQUIREMENTS/thing-templates.md

For the terminology definition we can start with what is written in the annex C of the TD spec and refine as necessary.

> A Thing Description Template is a description for a class of Things. It describes the properties, actions, events and common metadata that are shared for an entire group of Things, to enable the common handling of thousands of devices by a cloud server, which is not practical on a per-Thing basis. The Thing Description Template uses the same core vocabulary and information model from § 5. TD Information Model.

**Comment by egekorkan** [comment]
From the Scripting perspective, the produce() method gets something that one would call a TD template but it is not necessarily for a class of devices, it could be for a custom device implementation where some information is filled by the runtime.

Indeed, the discussion should continue in Architecture call.

**Comment by relu91** [comment]
I really enjoy listening about this topic in the latest F2F meeting. Just a couple of comments also from my side. 

I think that the TD model properties can be grouped into two categories: the WHATs and the HOWs.  
The former answer the question What is this thing? (hence the name) ; for example title, description, the list of properties/actions/events and their data schema. The latter are those who respond to How can I access this Thing? for example forms, security, base, etc. Therefore, HOWs are more implementation-specific while WHATs are more abstract.

I believe that a TDT should contain only the Whats and not the Hows, that's why agree with @egekorkan comment to not have hrefs. This may restrict the expressiveness of TDT (i.e. I cannot state that this "category" of things has COAP protocol binding) but it will improve their reusability. 

About inheritance, one simple and maybe effective solution could just define an application order (like is done similarly in Scala with traits/mixins). 

Finally, if TDTs could be also linked to actual behavior (i.e. code). Consequently, they could be also used like "libraries" and be imported in other scripts. I guess it stresses a little bit the idea, but in future it might help the modularization of scripts based on Scripting APIs.

**Comment by sebastiankb** [comment]
I think a simple explanation for a TDT may be that a TDT does not contain enough information to interact with a real Thing.

**Comment by sebastiankb** [comment]
I'm not sure if I'm agree that communication metadata should not be relevant for TDT. Lets assume you want to define a TDT for a device class where you can already provide all interaction affordances. If the device use JSON and HTTP with fix URL paths for the interactions then you can also provide the forms with `contentType` and `href` with the relative URL information. Only the base term is omitted. 
To create a TD instance of the TDT of the device class you have only to provide a base with the concrete IP address of the Thing.

This means that there are use cases in which parts of the communication metadata can be made available in TDTs.

**Comment by egekorkan** [comment]
> a TDT does not contain enough information to interact with a real Thing.

I think this is going in the right direction. I would add also "identify or interact with a real Thing". I also think that this is something everyone is somewhat agreeing on. Then, we would define more concrete cases like not having security if not needed, not having href if ip address and protocol not important, not having contentType etc. Any combination of those would meet the requirements of different people but we would all agree at least on the definition.

**Comment by sebastiankb** [comment]
A TDT does not contain enough information to identify or interact with a real Thing.

**Comment by relu91** [comment]
> A TDT does not contain enough information to identify or interact with a real Thing.

Really concise and clean, I like it! However, I want to little bit expand my previous point. I understand the use case you described and also I agree that users will have this necessity. On the other hand, I tend to consider it a bad design choice. Let me explain. 

Protocol bindings properties smell like an implementation detail. What if in the next firmware I use MQTT instead of HTTP for events. I have to create another version of the TDT which will describe the new protocol. So, this may lead to a multitude of LampHTTP.tdt, LampHTTPAndMQTT.tdt etc .

I know that versioning could help, but allowing this "degree of freedom" could be a double-edged sword (ie. a proliferation of TDTs and unmanageability of WoT projects). The WHATs properties change less and also could be better used to characterize classes of TDs.  I also believe that enforcing good architecture design choices at the definition phase, help the WoT software ecosystem a lot.  

Finally, I am not saying that is pointless to let users define protocol bindings specific properties, I am just afraid that it will get a little messy in the long run 😊.

**Comment by zolkis** [comment]
> A TDT does not contain enough information to identify or interact with a real Thing. 

Which is the reason the init dictionary given to produce() in Scripting is more than a TDT.
So we will not use the TDT term in Scripting and will place a Note about this.

**Comment by mlagally** [comment]
@zolkis Thanks for ths clarification. What is your working definition of an "init dict"? Is this an abbreviation, or the term you will use going forward?

**Comment by zolkis** [comment]
It is the dictionary object passed as an initialization argument to the [produce() ](https://w3c.github.io/wot-scripting-api/#the-produce-method) method in the Scripting API.

**Comment by danielpeintner** [comment]
> It is the dictionary object passed as an initialization argument to the [produce() ](https://w3c.github.io/wot-scripting-api/#the-produce-method) method in the Scripting API.

There seem to be many terms used in different areas (TD template, partial TD, init dictionary) which tend to be very very similar. In the case of scripting the "init dict" (I could also live with partial TD) is what gets passed to the WoT runtime that fills in runtime related information like the actual href for URIs et cetera.

I am a bit unsure  how we deal with *all* these terms...

**Comment by zolkis** [comment]
In the context of Scripting, an init dictionary is a common term. It is not used elsewhere.

A "partial TD" or "TD fragment" does not necessarily need to be defined as a WoT term, it could be used as a common term, meaning "any subset of a TD" (of subset of clauses and sub-clauses). It could be used in the context of all WoT specs.

An "init dictionary" for produce() can be created from a "partial TD" or "TD fragment". That is only relevant in the produce() algorithm. Also, a "partial TD" or "TD fragment" can be used as a filter in the discover() call in Scripting. Anyway these are well contained in Scripting context.

A "TD template" needs to be well defined in WoT for everyone to use.

**Comment by mlagally** [comment]
Let's have a terminology discussion in this week's architecture call.
It is important to sort out the terminology we are using for the different purposes.

Please prepare a definition for the term(s) you would like to see in the architecture spec. We can debate which name to use in the call.

**Comment by egekorkan** [comment]
As a way to speed up the discussions, we should maybe first talk about what is not a template. I think there is more consensus on this point.

**Comment by sebastiankb** [comment]
@zolkis 
>Which is the reason the init dictionary given to produce() in Scripting is more than a TDT.

Can you give concrete examples what is 'more' in an 'init dictionary' compared to a TDT then?

Be aware when you pass 'parts' of the TD to the produce() it is not complete in sense of our TD spec, e.g., the full communication / security metadata is missing since this is typically manged by the underlying WoT runtime. In my opinion, a 'TDT' is characterized mainly by that fact and agrees with the statement 'TDT does not contain enough information to identify or interact with a real Thing.'  The thing.expose() initiates the passed TDT by providing all communication metadata and being identifiable in the network.

**Comment by zolkis** [comment]
> Can you give concrete examples what is 'more' in an 'init dictionary' compared to a TDT then?

The init dictionary for produce() is purely a SW construct, it may contain whatever information that is useful for creating a Thing, including instance specific data (handled as a _hint_ by the implementation). This is not specified yet.

A TDT can be used as an init object, but also a full TD can be used as an init object.
Also, it may be a subset of a TDT or a TD, but the app may add clauses, e.g. forms and security related, as application input on what implementations should try to select if available. Again, this is not specified.

It is the end result of expose() that should comply with the TD spec and that is the responsibility of the implementation. How we get there is Scripting specific, including the init dictionary which is provided by the app (a powerful app, since it's defining a TD via a script).

**Comment by sebastiankb** [comment]
>The init dictionary for produce() is purely a SW construct, it may contain whatever information that is useful for creating a Thing, including instance specific data (handled as a hint by the implementation). This is not specified yet.

I think we're going in circles. In my view, some instance specific data may also part of a TDT and will simple taken over when a TD is instantiated.

>A TDT can be used as an init object, but also a full TD can be used as an init object.

That is correct!

>Also, it may be a subset of a TDT or a TD, but the app may add clauses, e.g. forms and security related, as application input on what implementations should try to select if available. 

I'm not sure I got that right. It sounds like an overlay feature of an IDE that should not be directly related to a TDT.

I think, we should discuss if we want to reflect only the WHATs as @relu91 suggest or both the WHATs and partly the HOWs (only if desired) as motivated [here](https://github.com/w3c/wot-architecture/issues/454#issuecomment-600772252).

**Comment by mlagally** [comment]
Arch call 1 on 26.3.:
Proposal:
A Thing Description Template (TDT) is a description for a class of Things that have the same capabilities. 
It describes the properties, actions, events and common metadata that are shared for an entire group of Things.  A TDT does not contain enough information to identify or interact with a Thing instance. 
(potentially add the following: Note: A TD is an instance of one or more TDTs.)

**Comment by zolkis** [comment]
I think of the "init dictionary" as an implementation detail as it is not (fully) standardized yet.
It's a SW object that provides input to produce() and is validated by JSON schema.
What produce() will do with it should be specified by its algorithm.

Currently not much of that behaviour is standardized, which means it is implementation specific today. We need to gather more experience from various implementations to figure out what makes sense to standardize (as clauses of the [produce() algorithm](https://w3c.github.io/wot-scripting-api/#the-produce-method) which currently refers to the [ExposedThing constructor](https://w3c.github.io/wot-scripting-api/#constructing-exposedthing).

So far the ExposedThing is just a SW object (invalid as Thing).
It is only the [expose() algorithm](https://w3c.github.io/wot-scripting-api/#the-expose-method) that will actually process the input (expand and validate it, then generate bindings).
The [expand steps](https://w3c.github.io/wot-scripting-api/#dfn-expand-a-td) will just add/complete the default values from the TD spec.
The [validate steps](https://w3c.github.io/wot-scripting-api/#validating-a-thing-description) currently just mean JSON schema validation as defined in the TD spec.
The art of creating a Thing from the "init dictionary" is almost completely encapsulated by the implementations today.

So the "init dictionary" is not standardized yet, but in principle is purely a SW object, an argument to a function. I suggest don't be distracted by "init dictionary" for now. We can define that after we define TDT.

**Comment by egekorkan** [comment]
> We need to gather more experience from various implementations to figure out what makes sense to standardize (as clauses of the produce() algorithm which currently refers to the ExposedThing constructor.

I do agree with this. At the same time, I think Scripting has the biggest use case of a SW object or document that generates a concrete Thing implementation and a TD.

**Comment by danielpeintner** [comment]
> I think of the "init dictionary" as an implementation detail as it is not (fully) standardized yet.
> It's a SW object that provides input to produce() and is validated by JSON schema.

Mhh, I am not sure if I can fully agree. From the implementation point of view node-wot for example tries to fulfill this init dictionary (partial TD) as much as possible. In some areas it cannot do so (e.g., the URIs are created by the runtime)

> What produce() will do with it should be specified by its algorithm.

This is true. It is not yet fully specified *which* information the runtime needs to respect and which not.

**Comment by zolkis** [comment]
> From the implementation point of view node-wot for example tries to fulfill this init dictionary (partial TD) as much as possible. In some areas it cannot do so (e.g., the URIs are created by the runtime)

Yes, that was mentioned (the [expand steps](https://w3c.github.io/wot-scripting-api/#dfn-expand-a-td)).

**Comment by relu91** [comment]
> (potentially add the following: Note: A TD is an instance of one or more TDTs.)

In my point of view, the composability of TDTs is one of the most important features of them. It helps the discovery process (i.e. search things that implement this TDTs), it helps developers to organize logically various types of TD and it helps the interoperability (i.e. it is quite similar to a Thing Profile, although it doesn't specify all the implementation details ). Therefore, I'd totally add that note; it may even be the unique feature of TDTs which is another thing that differentiates them from Partial/Fragment TDs or init dict.

About init dictionaries, another example is that they could contain parameters that control the production and the expose process. Like we are discussing [here](https://github.com/eclipse/thingweb.node-wot/issues/195), they might have a boolean property that toggles if the servient should serve that TD or not.

**Comment by mlagally** [comment]
Arch call on Dev 17.:
We now use the term "Thing Model" consistenly across different TFs. The Spec already has a definition in the terminology section.
