### ISSUE TITLE
Wrap up Burlingame F2F Plugfest and Terminology "Servient"

### ISSUE THREAD

**Issue by Kazuo-Kajimoto** [w3c/wot-architecture#46]
At Sunnyvale F2F meeting hosted by Fujitsu in July 2015, terminology “Servient” was proposed first time by Johannes at TF-AP.
https://www.w3.org/WoT/IG/wiki/F2F_meeting_29-31_July_2015_in_Sunnyvale_CA
https://www.w3.org/WoT/IG/wiki/images/3/33/Sunnyvale_F2F_TF-AP_breakout.pdf

Regarding “Building Block”, client and server looks symmetry and they will be cascaded to work together.
Then we assumed the node which works as both client and server.
So introducing new terminology “Servient” which combines “Server” and “Client”.
This “Servient” is very convenient to represent common building block.

In WoT IG/WG, “Servient” is common sense. On the other hand, it is new terminology.
So, it might be tough to understand the concept of “Servient” by other guys such as Mozilla.

In architecture document or in complementary document, describing servient use case might be helpful to understand what is Servient.

I think of 2 types of servient use cases as follows
1) Orchestrating Servers
2) Proxy
[WoT-Servient and Proxy.pptx](https://github.com/w3c/wot-architecture/files/1489436/WoT-Servient.and.Proxy.pptx)

**Comment by mryuichi** [comment]
We have already re-defined the terminology "Servient"in the plugfest calls, please see 2.1 "4-layered servients" in the plugfest preparation document below.
https://github.com/w3c/wot/blob/master/plugfest/2017-burlingame/preparation.md

This document gave the short definition for Application, Remote/Local Proxy and Device servients and their roles. It also gave the sequence diagrams among servients in the appendix that described the roles of remote and local servients. We need further discussion since Siemens had another implementation shown in the Sunnyvale plugfest.

The plugfest guideline document for the next plugfest will be done until Jan. of 2018 and make clear the  Inter-servient interface, the roles of the servients and some more issues to be resolved then. This work should be synchronized with architecture-tf.

**Comment by mkovatsc** [comment]
@mryuichi As I understood it, the original comment was not on having more precision on the Servient's role, but to replace the term "Servient" completely with a more well-known term such as "Node" or, probably better, "WoT Node".

We can then get more precise through "WoT Server", "WoT Client", "WoT Proxy", and even "WoT Servient" to be more precise about the exact role.

**Comment by mkovatsc** [comment]
An issue in the opposite direction I see is our maybe to specific definition of the common term "Thing". It also also a term in the IoT and there has been some work in the T2TRG recently to come up with a definition:

> An IoT “Thing” is a node on the Internet that has a foot in the **physical world** (and not just for talking to humans), often with a narrow purpose

> Constrainedness is often a property of “Things”, but certainly not always (design for scale)

To also get more aligned with the [Web Thing Model](https://www.w3.org/Submission/wot-model/) again (which is cited by many outside the W3C), it might be good to revert to the term "Web Thing" for our definition:

> An abstraction of a physical or virtual entity whose metadata and interfaces are described by a WoT Thing Description. This entity can be an existing device augmented with a Thing Description, a logical component of a device that has a software stack that natively provides Thing Descriptions (see Servient), a local hardware component of a Servient, or a logical entity (e.g., location) that does not directly provide any software stack such as a room or building.

Also note "Web Thing" definition in the [Web Thing Model](https://www.w3.org/Submission/wot-model/#conformance):

> A Web Thing (or simply Thing) is a digital representation of a physical object accessible via a RESTful Web API. Examples of Web Things are: an Arduino board, a garage door, a bottle of soda, a building, a TV, etc. The API of the Web Thing can be hosted on the Thing itself or on an intermediate host in the network such as a Gateway or a Cloud service (for Things that aren't accessible through the Internet). 

Also see my [slides from the Santa Clara F2F](https://www.w3.org/2017/02/wot-f2f/slides/2017_F2F-HATEOAS.pdf), where I showed how close both models actually are (6ff.).

**Comment by mmccool** [comment]
I was the person who brought up the issue and suggested "Node" instead of "Servient".  The issue is simply that "Servient" is a coinage and therefore you have to explain it to people.   It makes the WoT seem more complex than it is.  So I suggested "Node" as replacement, and yes, it would be a generic term covering Clients, Servers, and Servients.   So we would still have "Servient" in there, but it would be a sub-category of a more general concept, a "Node".

As for the relationship between "Node" and "Thing", a Thing would be a more general concept.  A Thing is anything that can have a Thing Description.  As defined, Thing Descriptions might define Things without network interfaces (eg without interactions), eg locations.   I think this will be relatively rare, so most of the time Nodes and Things will be the same in practice, but the distinction is enough to have separate terms: a Node is a Thing supporting a network interface (a non-empty set of interactions).

Another way a Node and a Thing might be different: we *might* want to also define a WoT Node to be something that hosts a WoT runtime and can execute WoT scripts.   In this case Nodes and Things would not have as much overlap, since there might be Things (such as OCF devices that we have generated TDs for...) that have Thing Descriptions (and so are Things) but do not have a WoT Runtime inside them (and so can only be WoT Servers, not WoT Clients, among other restrictions).

**Comment by mmccool** [comment]
Also, I don't thing we want to restrict Things (or Nodes) to RESTful APIs.  There could be MQTT Things, for instance.

**Comment by mmccool** [comment]
Then there's this, from the [OpenFog glossary of terms](https://www.openfogconsortium.org/wp-content/uploads/OpenFog-Consortium-glossary-of-terms-1.pdf).  I will admit that most definitions of thing include "physicality" ... but in practice, I expect people to bend that and have "virtual Things" or "abstract Things" (eg prototypes).  I don't think we have to be too fussy about this point.

> Thing Generally speaking, any physical object. In the
> term ‘Internet of Things’ however, it denotes the
> same concept as a Physical Entity.

**Comment by zolkis** [comment]
Certainly the term 'servient' has history with the IG and WG, but also I've always been thinking along the same line as @mmccool: 'servient' is a new WoT-specific term and needs explanation, whereas (WoT) 'node' is a well known term that fits well and also correctly implies the Thing is part of a network in the given context. We could still refer to 'servient' as a synonym, but I also think using 'WoT node' or 'node' would be more clear. 

However, a 'node' is often associated with a network element from the perspective of the network, and in WoT case such a node could run multiple Things, and multiple WoT SW stacks, so in this context 'node' would not be specific enough. Perhaps we could say 'host' to refer to the HW that runs the 

Also, one aspect to catch is the relationship of a network endpoint (e.g. IP address+port) with device/node, runtime (SW stack), Thing, interaction.

Also, what is the term when we refer to the SW stack that implements WoT functionality. It used to be 'servient', now is that also 'node', or could we use the term 'WoT runtime' for that as well (scripting may or may not be part of that: scripts run in execution contexts).

**Comment by mlagally** [comment]
@Kazuo-Kajimoto @mryuichi @mkovatsc @mmccool @zolkis I assume the terminology is settled by now. Please review and let me know if there is still an issue.
