### ISSUE TITLE
Define lifecycle states + definitions+actors+security data in a table

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#476]
Lifecycle diagram:
https://github.com/w3c/wot-architecture/blob/master/proposals/unified%20device%20lifecycle.drawio
Define the meaning of the states
Relationship + Capabilities in each state

**Comment by mlagally** [comment]
Please evolve: https://github.com/w3c/wot-architecture/blob/master/proposals/lifecycle-states.md

**Comment by zolkis** [comment]
### Manufactured state
**Why**: device is manufactured and flashed with a SW image. Possibly certified (e.g. OCF).
**Actor** responsible to get to this state: manufacturer
**Capabilities**:
- manufacturer certificate: optional
    (OCF: optional, OneM2M: optional, LwM2M: optional, T2TRG: optional, OPC-UA: TBC(*), Anima: TBC)
- identity: usually none, possibly manufacturer-default
- operational level: only for onboarding (OCF), initial provisioning (M2M), bootstrap (LwM2M), bootstrapping (installation, commisioning in T2TRG)
- external interfaces: native mechanisms (e.g. support for onboarding methods/discovery)
**Previous state**: none
**Preceding states** (from which one can reset to Manufactured state): any state except Destroyed
**Next states**: Bootstrapped/Onboarded
**Relationship** (why to change state): 
  - onboard the device in order to be usable by a provider (or to re-badge by vendor)
  - security setup
**Actor** who triggers next state transition: provider/vendor, based on native built-in mechanisms and protocols.

(*) to be checked

**Comment by zolkis** [comment]
### Onboarded state (for given protocol)
**Why**: device gets owned, gets identity.
**Actor** responsible to get to this state: provider/vendor
**Capabilities**:
- identity: given by new owner (provider/vendor or user)
- operational level: native, usually modified SW image, run after rebooting the device. After onboarding is complete, it can identify and authenticate, can be configured for services. 
- operational for WoT: no
- external interfaces: native mechanisms (e.g. support for further provisioning/configuration)

**Previous state**: Manufactured 
**Preceding states** (from which one can reset to Bootstrapped state): Operational/Maintenance
**Next states**: Operational, Manufactured
**Relationship** (why to change state to Operational): 
  - provision the device in order to be usable by a provider in a solution
  - security setup

**Relationship** (why to change state to Manufactured): 
  - "offboarding" the device, i.e. reset to factory defaults

**Actor** who triggers next state transition: provider/vendor or user, based on native built-in mechanisms and protocols.

**Comment by zolkis** [comment]
### Operational state (for given protocol)
**Why**: device gets operational in its native protocol (provisioned and configured).
**Actor** responsible to get to this state: provider/vendor
**Capabilities**:
- identity: given by new owner (provider/vendor or user)
- provisioned for the solution
- configured for the solution
- operational level: native, fully functional. 
- operational for WoT: no
- external interfaces: native mechanisms.

**Previous state**: Onboarded 
**Preceding states**: Onboarded, Maintenance (Non-operational for maintenance)
**Next states**: Maintenance, Onboarded (de-commission), Manufactured (reset to factory defaults)
**Relationship** (why to change state to Maintenance): 
  - run the native mechanisms for SW update or reconfiguration or re-provisioning that requires stopping the normal operation of the device, including eventual rebooting)
  - security setup

**Relationship** (why to change state to Onboarded): 
  - decommissioning the device, i.e. change solution or user but stay under the same owner (provider or user).

**Relationship** (why to change state to Manufactured): 
  - "offboarding" the device, i.e. reset to factory defaults

**Actor** who triggers next state transition: provider/vendor or user, based on native built-in mechanisms and protocols.

**Comment by zolkis** [comment]
### Operational state for WoT
**Why**: device gets operational for WoT
**Actor** responsible to get to this state: provider/vendor or user
**Capabilities**:
- identity: given by provider/vendor or user
- provisioned for the solution
- configured for the solution
- operational level: native, fully functional. 
- operational for WoT: yes (including deploying WoT runtime, dependencies and system configuration, optionally WoT bootstrapping for WoT services, e.g. Thing Directory)
- external interfaces: mainly WoT interface

**Previous state**: Operational for [protocol] 
**Preceding states**: Operational for [protocol] , Maintenance (Non-operational for maintenance)
**Next states**: Maintenance, Operational for [protocol], Onboarded (de-commission), Manufactured (reset to factory defaults)
**Relationship** (why to change state to Maintenance): 
  - run the native mechanisms for SW update or reconfiguration or re-provisioning that requires stopping the normal operation of the device, including eventual rebooting)
  - managed either by the underlying native SW stack (to update that), or by WoT runtime (only to update WoT, if that requires stopping WoT services)
  - security setup

**Relationship** (why to change state to Operational for [protocol]): 
  - decommissioning the device from WoT but keep the native operation.

**Relationship** (why to change state to Onboarded): 
  - decommissioning the device, i.e. change solution or user but stay under the same owner (provider or user).

**Relationship** (why to change state to Manufactured): 
  - "offboarding" the device, i.e. reset to factory defaults

**Actor** who triggers next state transition: provider/vendor or user, based on native built-in mechanisms and protocols.

**Comment by zolkis** [comment]
### Maintenance state (non-operational for [protocol])
**Why**: device gets SW updates, possibly including new configuration
**Actor** responsible to get to this state: provider/vendor or user
**Capabilities**:
- identity: given by provider/vendor or user
- provisioned for the solution
- configured for the solution
- operational level: native, under SW update
- operational for WoT: no 
- external interfaces: native maintenance interface

**Previous state**: Operational for [protocol], Operational for WoT
**Preceding states**: Operational for [protocol] , Operational for WoT
**Next states**: Operational for [protocol], Operational for WoT, Onboarded (de-commission), Manufactured (reset to factory defaults)
**Relationship** (why to change state to Operational for [protocol]): 
  - SW update finished, resuming operations.

**Relationship** (why to change state to Operational for WoT): 
  - SW update finished, resuming operations.

**Relationship** (why to change state to Onboarded):
  - decommissioning the device, i.e. change solution or user but stay under the same owner (provider or user).

**Relationship** (why to change state to Manufactured): 
  - "offboarding" the device, i.e. reset to factory defaults

**Actor** who triggers next state transition: provider/vendor or user, based on native built-in mechanisms and protocols.

**Comment by zolkis** [comment]
### Destroyed state 
**Why**: device gets destroyed with no further possibility of functioning
**Actor** responsible to get to this state: provider/vendor or user, enforcement agent
**Capabilities**: none
**Previous state**: any
**Preceding states**: any
**Next states**: none
**Relationship** (why to change state to Destroyed): 
  - end of life for device
  - callback for being dangerous
  - because enforcement (by your favorite dictator, or influencer)

**Actor** who triggers next state transition: manufacturer, provider/vendor or user, or enforcement agent, based on native built-in mechanisms and protocols.

**Comment by zolkis** [comment]
Please add comments, state proposals, modification suggestions.

**Comment by mmccool** [comment]
In the security call we discussed the following:
- We need to better define "authentication" and where it is needed
- Authentication is validation of expectations
- In the lifecycle table, we should note what expectations need to be validated for each state
Once that is done, we will review as part of issue https://github.com/w3c/wot-security/issues/148 to ensure that the topic of authentication has been addressed and better defined and scoped.

**Comment by ereshetova** [comment]
Unfortunately I have not been in the security call this week, so I don't actually know the background behind the points Michael raised here, so I am really not the best assignee here.

**Comment by mlagally** [comment]
There was a significant contribution by @zolkis to the lifecycle chapter which addresses these issues.
Closing in arch call on 7.10.
