### ISSUE TITLE
Requirement document for Agriculture

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#479]
Capturing the discussion in arch call on 9.4.:

- device virtualisation (device may be offline)
- units with clear reference points and defaults, e.g. SI units (for location, temperature, time, ...)
- states: (running, stopping, sleeping, available, disabled)
-> check automotive vehicle API (W3C candidate recommendation)
-> generic sensor API
-> Genivi Definitions
-> Talk with Benjamin Klotz

Potential external references:
https://genivi.github.io/vehicle_signal_specification/rule_set/data_entry/data_unit_types/
Small devices with limited resources - sensorML defines a common set of units for embedded systems
https://qudt.org/ ontologies for Units of Measure, Quantity Kinds, Dimensions and Types
Consider using: https://tools.ietf.org/html/rfc8428
TD spec currently uses "om" in the examples.

Need to select a default (could also be done in a profile) and define a standardized way for an override for specific markets.

**Comment by mlagally** [comment]
Arch Call2 on 9.4.:
At Lyon TPAC we looked into a variety of ontologies. A set of candidates was considered but no choice was made.
Standardising on a specific default could be part of a profile. To be discussed in the profiles requirements.

**Comment by mryuichi** [comment]
Create initial draft of requirements derived from the argriculture use case.
Threre are three types of requirements in the folloing.

(sorry, I cannot participate arch call1 on 30.4)

## Title: <title>
  
Requiremnens for the device virtualization, TD states, and Units in TD

### Submitter(s): 

Ryuichi Matsukura

### Reviewer(s):

<reviewers>

### Tracker Issue ID:

<please leave blank>

### Use case reference(s):

https://github.com/w3c/wot-architecture/blob/master/USE-CASES/smart-agriculture.md

### Affected WoT Deliverables:

Architecture
Thing Description
Profile

### Requirements:

- device virtualization<br>
Enable to respond to the requests from consumers instead of the orignal correspoding to the virtual device and beeing offline<br>
Create and keep TD for a virtual device that has the same interaction affordances as those of the original thing, but the different URL that points to the intermidiary

- States for things (devices)<br>
Enable to maintain states of things in TD<br>
  for examples, such states should be managed:<br>
  - running: thing is available (has valid URL) and able to reply to consumers's requests<br.
  - sleeping: thing is available (has valid URL) but able to reply to consumers's requests becuase of it(device) suspending<br>
  - stopping: thing is disabled (has no URL)
  
Comments: may separete discussions for states during onbording process to states after onboarding. Perhaps application developpers have much interested in states after onborading.

- units
Enabel to refer the definitions for unit specifined in a various standards

### Related standards:

<list related standards>

### Other references:

<additional references that provide more context>

### Comments:

<additional comments>

**Comment by mlagally** [comment]
Arch call on 17.12.:
This has been addressed and resolved some time ago.
