### ISSUE TITLE
Thing Discovery

### ISSUE THREAD

**Issue by NZSmartie** [w3c/wot-architecture#48]
Discovery is mentioned in the scripting API and would obviously be part of Thing Resource Directory (when that is started). 
There is a lack of discussion about how to discover Web of Things on various networks.

I'm strongly aware of using CoRE ([RFC 6690](https://tools.ietf.org/html/rfc6690)) `/.well-known/core` to list resources on a server. which may list Web of Thing resources and Thing Descriptors.  A CoRE link format lists resources and additional parameters to include metadata about resources. we could use linked resources by use of `describedby=` with a [IANA registered resource-type](https://www.iana.org/assignments/core-parameters/core-parameters.xhtml#rt-link-target-att-value) `rt=`. 

Also, use of CoRE's `.well-known/core` resource is part of CoAP ([RFC 7252](https://tools.ietf.org/html/rfc7252)) as part of resource discovery. 

A means of getting started on either Things directory or how the discovery process would work and what to look for would be a great way to start implementing real world devices.

**Comment by NZSmartie** [comment]
hello?

**Comment by zolkis** [comment]
[ Sorry, looks like everyone is busy. If there is no answer for long time, I suggest you participate at the [WG call](https://www.w3.org/WoT/IG/wiki/Main_Page#Main_WoT_WebConf) and ask there. ]

You might get a better answer from someone else, just a few quick remarks until that happens:
- WoT Discovery has been extensively discussed in the [IG](https://github.com/w3c/wot).
- Thing Directory is considered an _application_ for WoT, an optional part in a WoT solution.
- The Scripting API is an umbrella, it does not specify how to implement the underlying runtime, it just supports what is theoretically possible (and many of its methods might fail in a given network). It is work in progress.
- On OCF interop. On the plugfests, there have been WoT demos in an OCF network, the underlying implementation being based on [iotivity-node](https://github.com/otcshare/iotivity-node) and [REST server](https://github.com/intel/iot-rest-api-server). AFAICT, all OCF discovery methods should work with WoT. 
- One can make WoT solution implementations based on [node-wot](https://github.com/thingweb/node-wot), the de-facto reference implementation of WoT. There is also a reference implementation of a [Thing Directory](https://github.com/thingweb/thingweb-directory). One can explore the other projects in [thingweb](https://github.com/thingweb) as well.

**Comment by mkovatsc** [comment]
The main discovery mechanism is similar to the Web: following links. The Thing Directory is for registering managing such links (or rather resources that represent a Thing in case you follow the RD discussions in CoRE).

We are about to [register the media type](https://w3c.github.io/wot-thing-description/#iana-section) `application/td+json`, which can then be used in the `type` attribute of any link serialization to mark the target resource as Thing representation (a WoT Thing Description).

We have a [running verison](http://plugfest.thingweb.io/) of the [Thingweb Directory](https://github.com/thingweb/thingweb-directory). Unfortunately, we have been to busy the specifications lately, so that it is a bit oudated at the moment. Once we have the CR transition, we need to update the Directory for the test cases anyway.

**Comment by mmccool** [comment]
Since we have a Discovery TF now, followup on this issue should probably be directed there.   And I think the results of the Discovery TF should allow this issue to be closed (when complete?).   At any rate, see https://www.w3.org/WoT/IG/wiki/Discovery_TF and https://github.com/w3c/wot-discovery

**Comment by mlagally** [comment]
Arch call on Oct 20th:
Agree to close
