### ISSUE TITLE
Create Energy Efficiency for Smart Buildings Use Case

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-architecture#481]
Related to Fraunhofer's use case motivating their LinkSmart project, capture a use case for energy efficiency in Smart Buildings.  May be related to https://github.com/w3c/wot-architecture/issues/460
Links:
* https://raw.githubusercontent.com/wiki/linksmart/thing-directory/presentations/thing-directory-wot-call-2020-4-15.pdf
* https://github.com/linksmart

**Comment by mmccool** [comment]
Talked to Fraunhofer in the Discovery meeting, pointed them at the use-case template, and they agreed to work something up and create a PR.  I suggested the name smartbuilding-energy-efficiency.md.   I'll also email them a link to this issue. I'm not sure what their github handles are but when we find out we can also assign this issue to them.

**Comment by farshidtz** [comment]
Working on it in a [fork](https://github.com/farshidtz/wot-architecture/blob/smartbuilding-energy-efficiency/USE-CASES/connected-building-energy-efficiency.md). Will create a PR when ready. I propose connected-building-energy-efficiency.md as the name because there is no building automation involved.

**Comment by mlagally** [comment]
The use case descrition was created by Farshid. Closing the issue.
