### ISSUE TITLE
Terminology: thing description fragments

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#574]
Should we also define "thing description fragments"?
This is relevant for the Scripting TF.
@zolkis @danielpeintner Can you please comment and compare to the Thing Model definition.

**Comment by zolkis** [comment]
The partial objects used in the Scripting API do not need to be defined in Architecture IMO. They are script-specific constructs.

Inside Scripting, we might want to check the use of Thing Model definition, though.

**Comment by danielpeintner** [comment]
I agree with Zoltan.
Having said that, we still might want to discuss this in the scripting API call and I put it on the [agenda](https://www.w3.org/WoT/IG/wiki/WG_WoT_Scripting_API_WebConf#14_December_2020).

**Comment by mlagally** [comment]
TD framents are also used for queries in a directory. 

Potential definition: A "TD fragment"  is a JSON document that [has some missing parts but] satisfies some parts of a TD schema.

**Comment by zolkis** [comment]
Consider augmenting the definition with the main use cases: directory search, creating Things, ...

**Comment by relu91** [comment]
I am ok to provide a formal definition since there's always a little bit of confusion when initializing an Exposed thing with "something that was like a TD but not actually". Most of the time people were asking is that a TD template (the new TD Model) or just a JSON dictionary? 

Having a nice definition would end this impasse. 😄 I agree with @zolkis  that use cases would help readers to quickly grasp the concept. Additionally, we should think also about what is the minimal TD fragment. Is `{}` a TD fragment?

**Comment by danielpeintner** [comment]
Scripting Call 2021-01-11: 
* should look at examples: fragments are *very* generic like `{}` (essentially JSON Schema from TD without any required terms) while TD model might have _some requirements_
* Open point: How to differentiate fragments and TD model

**Comment by relu91** [comment]
Coming from the scripting API perspective the use case from fragments is mainly the creation of an ExposedThing object. The API specifies the following function for the purpose:
```ts
produce(td: ThingDescription): Promise<ExposedThing>;
```

Here we are using the term ThingDescription but in practice, it is just an alias for _every js object_:
```ts
export type ThingDescription = { [key: string]: any; };
```
**Note** that this is not true, Thing Description needs to satisfy the requirements defined in the TD JSONSchema. (e.g., `{}` it is not a valid thing description)

Here in the scripting API, we need something that hints at the structure of the next exposed TD but at the same time, it has not all the constraints of a full TD. An example is the following object:
```js
{
    title : "MyTemp",
    properties:{
        temperature: {}
    }
}
```
Then the runtime can fill up the blanks and instantiate a real TD from that. As I see this, the key characteristic of these objects is that they are runtime confined and they are mostly used once and forget. 


### Differences with Thing Model
The two concepts are really close to each other but I would say that ThingModel is a grown-up ThingFragment. As I said ThingFragments may make sense only in a scripting environment and are not serialized or published. ThingModel on the other hand are document types; they could be combined, imported, implemented by TDs, published in TDDs, etc. Since ThingModel requirements may grow in the future we cannot be sure that we'll define some TM-related property that should be always mandatory. On the other hand, a Thing Fragment may continue to be less restrictive and represent just what their name says: a piece of a Thing Description. 

In the end, the expose function of the Scripting API could accept both:
```ts
produce(td: ThingFragment | ThingModel): Promise<ExposedThing>;
```

Let's talk more about this in today's call.
