### ISSUE TITLE
New terminology for the Binding document?

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#575]
Is there any new terminology we should pull from the binding document to the architecture terminology section?

**Comment by egekorkan** [comment]
There are only 3 items in the terminology section of the Binding Templates document:

### TD Context Extension
> A mechanism to extend Thing Descriptions with additional Vocabulary Terms using `@context` as specified in JSON-LD[json-ld11]. It is the basis for semantic annotations and extensions to core mechanisms such as Protocol Bindings, Security Schemes, and Data Schemas. 
### Vocabulary
> A collection of Vocabulary Terms, identified by a namespace IRI. 
Term and Vocabulary Term
> A character string. When a Term is part of a Vocabulary, i.e., prefixed by a namespace IRI[RFC3987], it is called a Vocabulary Term. For the sake of readability, Vocabulary Terms present in this document are always written in a compact form and not as full IRIs. 

The last two are also in the TD spec and vocabulary is used as `Domain-specific Vocabulary` in the architecture spec. Since this is already in Architecture, why not move the context extension and Vocabulary Term there as well and also remove them from the TD spec and simply refer to the Architecture?

**Comment by mlagally** [comment]
Arch call on 10.12.:
We need to align the terms around "domain specific" vocabulary.
These 3 definitions should be carried over, @egekorkan, can you pelase create a MR?

**Comment by egekorkan** [comment]
This was actually resolved some time ago. There are no terminology in the binding spec. New ones should be synced via #614 anyway
