### ISSUE TITLE
New section on Security and Privacy considerations on Discovery

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#587]
need to mention DoS, ...

Will be done together when the discovery section is being added.

**Comment by mmccool** [comment]
Hmm... don't currently do this in my discovery PR, let me add...

**Comment by mmccool** [comment]
I have created a new issue to do a general review of S&P considerations for architecture (as we have just completed for Discovery and TD specs): https://github.com/w3c/wot-architecture/issues/726.  

For DDoS in particular, I just finished adding a detailed Security consideration to Discovery and don't want to duplicate that in Architecture.  However, a *general* statement in Architecture about "discouraging DDoS" might be useful, but I would not tie it to a particular deliverable (since the S&P sections in each deliverable are already about that deliverable specifically).

Propose closing this issue and consolidating this discussion under Issue #726.
