### ISSUE TITLE
`arch-id-correlation` : An identifier in the WoT Thing Description MUST allow for the correlation of multiple TDs representing the same original Thing or ultimately unique physical entity.

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#635]
Please follow the process in https://github.com/w3c/wot-architecture/issues/641

**Comment by benfrancis** [comment]
From https://github.com/w3c/wot-architecture/issues/625#issuecomment-970549428...

> * `arch-id-correlation` : An identifier in the WoT Thing Description MUST allow for the correlation of multiple TDs representing the same original Thing or ultimately unique physical entity.

I personally don't really agree with this assertion because in my opinion, as far as a WoT Consumer is concerned, two different Thing Descriptions hosted at two different URLs for the same physical device should be treated as two separate Web Things.

However, the Thing Description specification does define an `id` member of the Thing Description and there's nothing to stop two Thing Descriptions using the same `id`. It's currently not exactly clear what a Consumer should do in this situation, but let's continue that discussion in https://github.com/w3c/wot-discovery/issues/190.

I do think the term "correlation" in this assertion is a bit ambiguous.

**Conclusion:** ❌ I don't really agree with this assertion, but let's continue the discussion.

**Comment by k-toumura** [comment]
It we make it mandatory to be able to correlate IDs, there is a concern about privacy issues.
For use cases where the Intermediary is hiding the Things behind it, it may be worthwhile not to be able to correlate IDs.

**Comment by sebastiankb** [comment]
I think, the task of the TD is to provide the option for identification when required. 

@k-toumura 
>  For use cases where the Intermediary is hiding the Things behind it, it may be worthwhile not to be able to correlate IDs.

Yes and I think this is the task of an ecosystem which manages the Things and provides potential IDs. This should not be specified by a standard.

**Comment by sebastiankb** [comment]
from today's TD call
- this issue should be used to be more clear about the id field in the TD spec and its usages
- it seems also some impact on the discovery TF, @mmccool will take care of it

**Comment by mlagally** [comment]
Arch call on 25:11:
Need to improve text, discuss in TD, discovery

**Comment by mlagally** [comment]
Arch call on 16.12:
Did the discussion in TD and Discovery group happen?
Need to ask @mmccool , TD discussion seems to be still open

**Comment by mlagally** [comment]
Arch call on 19.5.:
@mmccool Please remove the assertion.

**Comment by farshidtz** [comment]
In the past, we've discussed this in length in https://github.com/w3c/wot-discovery/issues/190.

IMO, since Thing.id is the `@id` field of TD, we should respect the following [JSON-LD spec](https://www.w3.org/TR/json-ld/#syntax-tokens-and-keywords):

> @id
> Used to uniquely identify node objects that are being described in the document with IRIs or blank node identifiers.

The only way to let `@id` uniquely identify the node object (TD) is to consider `id` as the unique identifier of TD!

**Comment by mlagally** [comment]
@farshidtz 
We implemented the change requested by this issue. Further discussions about ids should be further continued in the TD-TF, if necesary.
