### ISSUE TITLE
`arch-consumer-configuration` : The configuration of the Consumer behavior MAY be exposed through the Thing.

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#636]
Please follow the process in https://github.com/w3c/wot-architecture/issues/641

**Comment by benfrancis** [comment]
From https://github.com/w3c/wot-architecture/issues/625#issuecomment-970549428...

> * `arch-consumer-configuration` : The configuration of the Consumer behavior MAY be exposed through the Thing.

> No idea how this happens. By looking at Fig 17, I still do not understand. What is even Consumer behavior, how is it configured and why can it be through a Thing...

I have no idea what this means either. If I had to guess I'd say it means that the configuration of a consumer could be exposed as properties in a Thing Description so that another Consumer can change its properties. If so then yes that's technically possible but probably not worth mentioning.


**Conclusion:** ❌ I don't exactly disagree, but it probably doesn't warrant a mention.

--- 
**Suggested action:** Remove the assertion.

**Comment by k-toumura** [comment]
There is no need to recommend exposing the consumer's configuration, so I think it is better to remove the assertion.   
This sentence may mean "Consumer can expose the behavior of bundled Things as a virtual Thing"...?
But either way, I think this sentence should be a general explanation, not an assertion.

**Comment by sebastiankb** [comment]
I'm not sure either. Maybe this is also kind of implementation dependent. E.g., node-wot provides some basic configuration in wot-servient.conf.json which, however, is confidential and should be not shared. 

I'm also ok to remove this assertion from the Arch spec.

**Comment by mlagally** [comment]
arch call on 25.11.
remove
