### ISSUE TITLE
`arch-methods` : Eligible protocols for W3C WoT MUST be based on a standard set of methods that are known a prior.

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#640]
Please follow the process described in https://github.com/w3c/wot-architecture/issues/641

**Comment by benfrancis** [comment]
From https://github.com/w3c/wot-architecture/issues/625#issuecomment-970549428...

> * `arch-methods` : Eligible protocols for W3C WoT MUST be based on a standard set of methods that are known a priori

This does kind of make sense, since otherwise how can a protocol binding be described in a form? Does MQTT really have "methods" though, or is that just an HTTP/CoAP thing? I think what this is getting at is that it has to be possible to create a vocabulary to describe the protocol in a Protocol Binding Template.

**Conclusion:** ✔️ I don't have a strong opinion, but this kind of makes sense.

---
**Suggested action**: Consider rewording the assertion and moving it to WoT Thing Description, or just remove it.

**Comment by mlagally** [comment]
arch call: 25.11: remove it completely
