### ISSUE TITLE
Identify normative RFC2119 assertions that affect the TD specification

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#642]
All normative assertions on the TD spec should be moved to the TD specification.

A first analysis has been done in https://github.com/w3c/wot-architecture/issues/625

A second review should be done to make sure we don't miss anything.

**Comment by mlagally** [comment]
Results should be documented as in:
https://github.com/w3c/wot-architecture/issues/625

**Comment by egekorkan** [comment]
Just to be precise, I did not do a review with the goal of moving assertions to the TD spec. I have looked at which assertions are unclear or incorrect. There are definitely more assertions that need to be moved to the TD spec

**Comment by benfrancis** [comment]
@sebastiankb Hi, if you work on this issue @egekorkan noted that the list of assertions which @mlagally generated from the WoT Architecture specification makes this task much easier https://github.com/w3c/wot-architecture/blob/main/testing/assertions.csv

Following a quick read almost all of these assertions seem to relate to the Thing Description specification, except for the last four which relate to the WoT Discovery specification.

Aside from those identified in #625, two that stood out to me are:

- _arch-hypermedia-protocol-binding "Protocol Bindings MUST be serialized as hypermedia controls to be self-descriptive on how to activate the Interaction Affordance."_
  - This rule is arguably now broken by the Core Profile in the WoT Profile specification which defines a concrete protocol binding which Thing Descriptions can opt into using the `profile` member, so that they don't have to be entirely self-descriptive. They still have to provide hypermedia controls (forms), but some of the details are provided out of band. The WoT Thing Description specification also does this to a lesser extent by defining defaults.
- _arch-media-type "All data (a.k.a. content) exchanged when activating Interaction Affordances MUST be identified by a media type [[!RFC2046]] in the Protocol Binding."_
  - Similarly, as I understand it this is not strictly true for forms which rely on the default application/json content type.

It didn't get as far as a resolution, but in the WoT Architecture call today there seemed to be a lot of support for removing all normative assertions from the WoT Architecture specification, either by moving them to the other normative specifications (WoT Thing Description, WoT Discovery and WoT Profile), or removing them entirely.

**Comment by mlagally** [comment]
@benfrancis 
I believe you misinterpreted the discussion in the architecture call as consensus. As we have split out them individually we now can make fast progress on resolving each of them.

I prefer this due diligence approach over just removing entire sections of text that has been concluded after long discussions because some of it needs to be clarified, improved, updated, removed, moved.

**Comment by sebastiankb** [comment]
@benfrancis yes can take this action. 

I will already prepare a PR in the TD repo to show how and where these assertions could be moved to the TD spec. We can discuss this in the next Arch call then.

**Comment by mlagally** [comment]
@sebastiankb 
In the last architecture call we broke down the assertions that were raised by Ege
into individual issues that are now being clarified.
It would make sense to identify appropriate locations for each of them, and create individual PRs for those that we identified to be moved.

A combined PR will be very difficult to review.

**Comment by mlagally** [comment]
@sebastiankb 
Please check if the current set of assertion issues that were raised by @egekorkan in https://github.com/w3c/wot-architecture/issues/625 are complete.
@benfrancis has identified additional issues, in total there are 42 assertions https://github.com/w3c/wot-architecture/blob/main/testing/assertions.csv

**Comment by mlagally** [comment]
Please review the sections that contain the assertions and propose a way forward.

**Comment by mlagally** [comment]
Arch call on 16.12:
@sebastiankb confirmed that the issue should be kept open. 
needs to check.

**Comment by mlagally** [comment]
Arch call on May 24th:
no further work expected.
