### ISSUE TITLE
Producer is missing in terminology section

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-architecture#656]
as @benfrancis noted in https://github.com/w3c/wot-thing-description/issues/1324 there is a "Consumer" definition, however, no one for "Producer".
 
Maybe this issue can be simple solved to add simple "Producer" in the title of  

![image](https://user-images.githubusercontent.com/13832739/146775782-22530880-6e36-40db-857e-a36862f77016.png)
 

So it comes  "Thing or Web Thing or Producer"

**Comment by mlagally** [comment]
Arch call on Dec 23rd:
TD Producer, could be a separate terminology entry, could also be manually written by a human.
it would be good to distinguish between producer and Thing for the cases where a TD of a Thing is produced by some other entity
"Exposing a TD" could also be worth defining
we should clearly define, "expose", "consume", "produce"
Skimming the architecture specification about the use of produce, consume should 
A thing exposes a TD, an application, consumer, intermediary consumes.
there is a possibility that we should identify which term would be better for which part

Where do we use the "expose" term? So far we used "consumer"/"producer", not sure about what discovery does

**Comment by mmccool** [comment]
We talked about this a bit in the Editor's call as I wanted to clarify how the term "Expose" is used in the Scripting API.  There was also some related discussion in Discovery a few months ago that I think is relevant.

Currently, "Expose" means "to make available the network API described by a Thing Description".  It does NOT mean "make the TD available", and I don't think we want to confuse the two.  In particular, in the Scripting API to "Expose a TD" just means to generate the network API described by the TD; it does NOT mean make it available for discovery.  I also mentioned that I think "Producer" has the problem that implies both "generation" and "providing" of the TD.  

So I would like to propose the following terms:
Exposer - The entity (Thing) that makes the affordances described by a Thing Description available on the network.
Provider - The entity that makes the Thing Description of a Thing available for Discovery.
Generator - The entity that creates the Thing Description for a Thing (for example, by instantiating a Thing Model with concrete parameters)

These may not all be the same entity.  For a self-describing Thing, it may be both "Provider" and "Exposer".  A Thing might also self-Generate its own TD if all it has to do is plug a base IP address into a TM.  In other cases these might all be separate.  For instance, a small device may have its TD Generated by an installer and registered in a Directory.  Then the installer is the Generator, the Directory is the Provider, but the device is the Exposer.

**Comment by benfrancis** [comment]
Thanks for breaking this down, @mmccool.

You are right that what I had in mind for "Producer" was simply the counterpart to "Consumer", which I assumed would carry out all three roles.

The definition of a Consumer:
> An entity that can process WoT Thing Descriptions (including its JSON-based representation format) and interact with Things (i.e., consume Things).

This implies that a "Consumer" both parses a Thing Description (the counterpart to generating it) and interacts with the affordances of the Thing it describes (the counterpart to exposing affordances). Perhaps a Consumer might discover a Thing too, by acting as a consumer of a discovery service (the distinction from "Discoverer" is still not clear to me, since that term sounds like the opposite of its definition).

It would be much easier to understand in the majority of cases if there was simply a Producer (which generates and provides a Thing Description and exposes its affordances) and a Consumer (which discovers and parses a Thing Description and interacts with its affordances), but I agree that in theory the three roles could be carried out by three separate entities and sometimes it's necessary to distinguish between them.

Note that the line from the Thing Description specification which sparked this discussion...

> Implementations of a TD Processor may be a TD producer only (able to serialize to TD Documents) or a TD consumer only (able to deserialize from TD Documents).

...implies that a "producer" can at least perform the generation part, so if the definition of producer does not include that function (or is not defined at all) then the Thing Description specification will need updating.

---

FWIW, in the Web Thing Protocol CG we so far just define the terms "WoT Client", "WoT Device" (aka "web thing"), "WoT Gateway" and "WoT Directory" which makes things more concrete, but I'm not going to open the "Servient" can of worms again!
