### ISSUE TITLE
Video, Audio treatment

### ISSUE THREAD

**Issue by Kazuo-Kajimoto** [w3c/wot-architecture#8]
Currently, we are discussing streaming. But this streaming means continuous sensor values.
On the other hand, from the consumer electronics manufacturer's point of view, we have not discussed how to treat audio/video streaming/downloading. This might be out of scope of WoT standardization, but as architecture document, I'd like to point out audio/video is out of scope or not.

**Comment by mkovatsc** [comment]
We should do it like the Web and be able to link it. Technically, it would be quite easy to have an interaction that links to an rtp:// URI, video/mp4 Media Type, etc. ... but it is another use case where Property/Action/Event does not fit.

**Comment by mmccool** [comment]
I think maybe we should create an issue (if it does not already exist) to consider "Stream" as a separate interaction pattern, but that issue should be under the wot-thing-description repo.   I also think it's a second-order issue since "Event" should cover a lot of the use cases pertaining to devices periodically generating updates.   But we may want a "Stream" interaction for things like AV streaming (eg RTP) with persistent connections; I do feel these are distinct from the others.

**Comment by draggett** [comment]
Streams introduce a requirement to be able to handle buffered updates at the API level, i.e. a means to get a notification with a buffer containing a sequence of property updates rather than requiring each update to be handled independently.  I've used this pattern for updating a scrolling display of multi-channel health sensor data.

**Comment by mlagally** [comment]
Streams are not excluded but beyond the current architecture document.
It is not forbidden by the architecture document, but nobody needed it in practice so far.

We keep this open until 20.2., will put into backlog after that. @draggett: can we close this?

**Comment by mlagally** [comment]
- Need to work closely with Media and Entertainment WG
- Security cameras have frequent security leaks
- Invite more people from Media / Entertainment
- hybrid cast, i.e. signalling only
- capture RTSP cameras

Anti requirement: We don't define own media and streaming protocol and signaling

**Comment by mlagally** [comment]
Discussion with Chris Needham(BBC):
- DLNA - consider description using WoT TD description?
- HbbTV - 
- Hybridcast 
- ATSC 
- DVB-SI
- MPEG Dash

There are various use cases, including Broadcast use cases / home use cases
We should not reinvent signaling etc.
Need an introductory meeting to exchange information between Media and Entertainment and WoT groups 
Let's organize an online meeting
Media Entertainment group has a lot of members from CE

**Comment by mlagally** [comment]
Joint phone conference with Media and Entertainment group should be used to identify use cases and stakeholders / contributors.

**Comment by mlagally** [comment]
Virtual F2F / Arch:
Combine and merge the issue / task with:
https://github.com/w3c/wot-architecture/issues/442
Future discussion should happen there.
