### ISSUE TITLE
Fix normative references / convert to informative, where applicable

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#809]
There are a number of normative references to non-normative documents - in [one case](https://w3c.github.io/wot-architecture/#bib-solid) to a document index rather than any specific specification - which need to be made into informative references.

**Comment by mlagally** [comment]
All normative references must be checked for that. I 'm sure the W3C tooling provides this information.

**Comment by mlagally** [comment]
Should be fixed as part of checks on creating the CR candidate.

**Comment by mmccool** [comment]
Regarding the SOLID reference specifically, it's referring to the index because the reference is to the project as a whole, not a specific standard.  However, SOLID is also a CG at present, and so has not published any normative specifications.  The simplest resolution is to mark the reference as informative.

There may be other references that should be modified to informative ones; we should look for these during the next two weeks during review.

**Comment by sebastiankb** [comment]
from today's main call: group decided to close
