### ISSUE TITLE
Compatibility in the ecosystem [TAG feedback]

### ISSUE THREAD

**Issue by rhiaro** [w3c/wot-architecture#814]
We can see a lot of work to survey the current (and, presumably, ever-changing) landscape of IoT devices, and the effort to bring fragmented ways of operating together. Can you summarise, or link to a summary of, what the compatibility story looks like in practice? Eg. what widely used devices would be compatible with this architecture out of the box? Or what would needed to be added to make them compatible? What is practically possible with what is out there today, if this suite of specs are published as-is? A few concrete examples would be really nice to help give us a better picture of the ecosystem.

(from https://github.com/w3ctag/design-reviews/issues/736)

**Comment by mlagally** [comment]
Out of the box interoperability is the primary goal of the Profile specification. We should highlight that in the introduction section and provide more information in the profile section, once the profile specification is finalized.

**Comment by mlagally** [comment]
Discussion in Arch call on 1. Sept:
Devices that use HTTP, CoAP or MQTT can be described with a Thing Description (TD).
Given a suitable TD, a consumer can interact with these devices out of the box.
There are other IoT devices that are more challenging, and need extensions beyond that, e.g. OPC-UA devices, but we are working with the OPC foundation to make this possible. This is planned for the next charter.
There are also protocol translators (gateways) for HTTP to other protocol standards, so the number of devices we can interact with is much larger because of this.

**Comment by mlagally** [comment]
Calling out particular devices for the ecosystem does not belong into a standard. We have anecdotal evidence of several systems adopting the specification, but putting this evidence as a snapshot of today's adoption would be outdated very quickly. 

This kind of information rather belongs to, and is already provided in the explainer document.
