### ISSUE TITLE
Removing redundant assertion csv files

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-architecture#898]
The arch repo has 3 csv files that are about assertions. Given that all assertions of the arch spec are manually tested, I do not see the need for having 3 and trying to keep them up to date.

1. https://github.com/w3c/wot-architecture/blob/main/testing/assertions.csv
2. https://github.com/w3c/wot-architecture/blob/main/testing/manual.csv
3. https://github.com/w3c/wot-architecture/blob/main/testing/template.csv

Only the first one is generated automatically and actually has 2 more assertions than the rest.

**Comment by egekorkan** [comment]
I have instructed using the first one in https://github.com/w3c/wot-testing/pull/537

**Comment by mmccool** [comment]
Actually, template.csv is generated automatically by the report generator.  It's true that manual.csv is sort of redundant in the case of Architecture (it's just a copy of template.csv...) but deleting it will break my report generation tool, since it looks for it.

I'm going to mark this as resolved - but without deleting those files.   Feel free to ignore them.

**Comment by mmccool** [comment]
BTW it is odd that assertions.csv is longer than template.csv, but it's the LATTER that is more up to date, as it is updated every time the report generator is run.  The extra assertions in assertions.csv are due to assertions that were removed.   I re-ran the script ("extractFile.js") that generates assertions.csv and will make a PR to update it.  After regeneration it is the same length as template.csv.
